import React,{useMemo,useState} from 'react';
import {createRoot} from 'react-dom/client';
import './styles.css';
type Project={id:number;name:string;path:string;mode:'Novo'|'Existente';status:string};
type Message={role:'user'|'agent';text:string};
const skills=['react-quality','typescript','browser-verifier','debugging','security-review','reviewer-loop'];
function App(){
 const [projects,setProjects]=useState<Project[]>([{id:1,name:'Meu primeiro projeto',path:'Ainda não configurado',mode:'Novo',status:'Rascunho'}]); const [active,setActive]=useState(1); const [messages,setMessages]=useState<Message[]>([{role:'agent',text:'Olá! Sou o Forge Agent. Descreva o que você quer construir ou use @ para ativar uma Skill.'}]); const [input,setInput]=useState(''); const [mode,setMode]=useState<'Novo'|'Existente'>('Novo'); const [preview,setPreview]=useState('A visualização aparecerá aqui quando o agente iniciar um projeto.'); const [busy,setBusy]=useState(false); const current=projects.find(p=>p.id===active); const mentions=useMemo(()=>skills.filter(s=>input.includes('@'+s)),[input]);
 async function send(){if(!input.trim())return;const text=input;setInput('');setMessages(m=>[...m,{role:'user',text}]);setBusy(true);try{const r=window.forge?await window.forge.run(text):{message:'Plano preparado para revisão.',outputs:['Quality Gates de código e interface incluídos.',mentions.length?`Skills acionadas: ${mentions.join(', ')}`:'Skills padrão selecionadas.'],plan:{goal:text,actions:[{type:'quality_gate'},{type:'browser_check'}]}};setMessages(m=>[...m,{role:'agent',text:[r.message,...(r.outputs||[])].join('\n')}]);setPreview('Preview preparado. Quality Gates e verificação visual aguardando execução.');}catch(e){setMessages(m=>[...m,{role:'agent',text:String(e)}])}finally{setBusy(false)}}
 function addProject(){const id=Date.now();setProjects(p=>[...p,{id,name:`Projeto ${p.length+1}`,path:'Ainda não configurado',mode:'Novo',status:'Rascunho'}]);setActive(id);setMessages([{role:'agent',text:'Novo projeto criado. O que vamos construir?'}])}
 function deleteProject(id:number){if(projects.length===1)return;const rest=projects.filter(p=>p.id!==id);setProjects(rest);if(active===id)setActive(rest[0].id)}
 return <main className="app-shell"><aside className="sidebar"><div className="brand">Forge<span>·</span>Agent</div><div className="side-caption">Workspace local</div><button className="new-chat" onClick={()=>setMessages([{role:'agent',text:'Nova conversa iniciada. Como posso ajudar?'}])}>＋ Nova conversa</button><div className="side-label">PROJETOS <button onClick={addProject}>＋</button></div><div className="project-list">{projects.map(p=><div className={'project-row '+(p.id===active?'chosen':'')} key={p.id} onClick={()=>setActive(p.id)}><div className="project-dot">{p.name[0]}</div><div className="project-name"><b>{p.name}</b><small>{p.status}</small></div><button className="delete" title="Excluir projeto" onClick={e=>{e.stopPropagation();deleteProject(p.id)}}>×</button></div>)}</div><div className="side-label">NAVEGAÇÃO</div><button className="side-link">◇ Skills</button><button className="side-link">◌ Histórico</button><div className="model-card"><b>Modelo ativo</b><small>UseOneAI<br/>Fallback: GPT-5.6 Luna</small></div></aside><section className="workspace"><header className="workspace-head"><div><span className="eyebrow">{current?.name}</span><h1>Construir com o agente</h1><p>Planeje, execute e reverifique em um único espaço.</p></div><div className="head-actions"><select value={mode} onChange={e=>setMode(e.target.value as 'Novo'|'Existente')}><option>Novo projeto</option><option>Projeto existente</option></select><button className="ghost" onClick={addProject}>＋ Projeto</button></div></header><div className="split"><div className="chat-panel"><div className="chat-head"><b>Conversa</b><span>{busy?'Processando…':'Pronto'}</span></div><div className="messages">{messages.map((m,i)=><div className={'message '+m.role} key={i}><div className="avatar">{m.role==='agent'?'F':'Você'}</div><div className="bubble">{m.text}</div></div>)}</div><div className="composer chat-composer"><textarea value={input} onChange={e=>setInput(e.target.value)} onKeyDown={e=>{if(e.key==='Enter'&&!e.shiftKey){e.preventDefault();send()}}} placeholder="Descreva o que construir… Use @typescript ou @browser-verifier"/><div className="composer-foot"><span>{mentions.length?`Ativas: ${mentions.join(', ')}`:'Enter para enviar · Shift+Enter para nova linha'}</span><button onClick={send} disabled={busy}>Enviar →</button></div></div></div><div className="preview-panel"><div className="preview-head"><b>Preview ao vivo</b><span>localhost</span></div><div className="preview-canvas"><div className="preview-placeholder"><div className="preview-icon">✦</div><b>{preview}</b><small>O agente exibirá o resultado e as evidências visuais aqui.</small></div></div><div className="checks"><b>Verificações</b><div><span>○</span> Testes de código <small>aguardando</small></div><div><span>○</span> Fluxo visual <small>aguardando</small></div><div><span>○</span> Reviewer Loop <small>aguardando</small></div></div></div></div></section></main>;
}
createRoot(document.getElementById('root')!).render(<App/>);

